services:
  postgres:
    image: postgres:15.3-alpine
    ports:
      - ${PG_PORT:-changeme}:${PG_PORT:-changeme}
    restart: no
    environment:
      - POSTGRES_DB=${PG_DATABASE:-changeme}
      - POSTGRES_USER=${PG_USERNAME:-changeme}
      - POSTGRES_PASSWORD=${PG_PASSWORD:-changeme}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --dbname=${PG_DATABASE:-changeme} --username=${PG_USERNAME:-changeme}"
        ]
      interval: 30s
      timeout: 5s
      retries: 5

  # pgadmin:
  #   image: dpage/pgadmin4:7.3
  #   depends_on:
  #     - postgres
  #   ports:
  #     - ${PGA_PORT:-changeme}:${PGA_PORT:-changeme}
  #   restart: no
  #   volumes:
  #     - ./volumes/pgadmin4:/volumes/pgadmin4
  #   environment:
  #     - PGADMIN_LISTEN_PORT=${PGA_PORT:-changeme}
  #     - PGADMIN_DEFAULT_EMAIL=${PGA_USERNAME:-changeme}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGA_PASSWORD:-changeme}
  #     - PGADMIN_SERVER_JSON_FILE=/volumes/pgadmin4/servers.json

  # hasura:
  #   image: hasura/graphql-engine:v2.20.0
  #   ports:
  #     - ${HSR_PORT:-changeme}:${HSR_PORT:-changeme}
  #   depends_on:
  #     - postgres
  #   restart: always
  #   environment:
  #     - HASURA_GRAPHQL_DATABASE_URL=postgres://${PG_USERNAME:-changeme}:${PG_PASSWORD:-changeme}@postgres:${PG_PORT:-changeme}/${PG_DATABASE:-changeme}
  #     - HASURA_GRAPHQL_ADMIN_SECRET=${HSR_GRAPHQL_ADMIN_SECRET:-changeme}
  #     - HASURA_GRAPHQL_ENABLE_CONSOLE=true
  #     - HASURA_GRAPHQL_DEV_MODE=false
  #     - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
  #     - HASURA_GRAPHQL_ENABLE_TELEMETRY=false

  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      # - hasura
    restart: no
    ports:
      - 8000:8000
    env_file:
      - .env