version: 2.1
jobs:
  build-docker-image:
    machine:
      image: ubuntu-2204:2022.04.1
    resource_class: xlarge
    environment:
      TAG: << pipeline.git.tag >>
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: true
      - run: docker login <containerRegistryURL>/<containerRegistryName> -u nologin -p $SCW_SECRET_KEY
      - run: docker build --tag <containerRegistryURL>/<containerRegistryName>/<applicationName>:$TAG <dockerFileFolder> | while read line; do echo "$(date +%T) > $line"; done;
  build-push-docker-image:
    machine:
      image: ubuntu-2204:2022.04.1
    resource_class: xlarge
    environment:
      TAG: << pipeline.git.tag >>
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: true
      - run: docker login <containerRegistryURL>/<containerRegistryName> -u nologin -p $SCW_SECRET_KEY
      - run: docker build --tag <containerRegistryURL>/<containerRegistryName>/<applicationName>:$TAG <dockerFileFolder> | while read line; do echo "$(date +%T) > $line"; done;
      - run: docker push <containerRegistryURL>/<containerRegistryName>/<applicationName>:$TAG

workflows:
  version: 2
  build:
    jobs:
      - build-docker-image:
          filters:
            tags:
              only: /^build.*/
            branches:
              ignore: /.*/
  build-and-register:
    jobs:
      - build-push-docker-image:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
