version: 2.1

orbs: 
  path-filtering: circleci/path-filtering@0.1.3
    
setup: true 

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          filters:
            branches:
              only:
                - performance-tests
          base-revision: <<pipeline.git.branch>>
          config-path: .circleci/workflows.yml
          ## BELOW TO BE CORRECTED IF NEEDED ##
          mapping: |
            app/.* app true 
            devops/.* devops true