
version: 2.1

parameters:
  working-directory:
    type: string
    description: Path of the working directory (default: /tmp/gitcode)
    default: /tmp/gitcode
  
  min-coverage:
    type: integer
    description: Minimun test coverage result expected in %
    default: <min-coverage-value>

jobs:
  npm_build-test-coverage:
    docker:
      - image: cimg/node:18.7.0
    working_directory: <<pipeline.parameters.working-directory>>
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "<<pipeline.parameters.working-directory>>/packages/hardhat/package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: npm install & build
          command: |
            cd <<pipeline.parameters.working-directory>>/packages/hardhat
            npm install
            npm run build
      - run:
          name: npm run test
          command: |
            cd <<pipeline.parameters.working-directory>>/packages/hardhat
            npm run test
      - run:
          name: npm run coverage
          command: |
            cd <<pipeline.parameters.working-directory>>/packages/hardhat
            npm run coverage
      - run:
          name: Install dart
          command: |
            sudo apt-get update && apt-get install apt-transport-https -y
            wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/dart.gpg
            echo 'deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main' | sudo tee /etc/apt/sources.list.d/dart_stable.list
            sudo apt-get update && apt-get install dart -y
      - run:
          name: Calculate code coverage
          command: |
            cd <<pipeline.parameters.working-directory>>/packages/hardhat
            dart run calculate_coverage.dart ./coverage/lcov.info <<pipeline.parameters.min-coverage>>
      
      - save_cache:
          paths:
            - <<pipeline.parameters.working-directory>>/packages/hardhat/node_modules 
          key: node-v1-{{ .Branch }}-{{ checksum "<<pipeline.parameters.working-directory>>/packages/hardhat/package-lock.json" }}
      
      - store_artifacts:
          path: <<pipeline.parameters.working-directory>>/packages/hardhat/coverage
      
      - persist_to_workspace:
          root: <<pipeline.parameters.working-directory>>/packages/
          paths:
            - hardhat

  foundry_test:
    docker:
      - image : ghcr.io/foundry-rs/foundry:latest
    working_directory: <<pipeline.parameters.working-directory>>
    steps:
      - checkout
      
      - attach_workspace:
          at: <<pipeline.parameters.working-directory>>/packages/
      
      - run:
          name: Run Foundry tests
          command: |
            cd <<pipeline.parameters.working-directory>>/packages/hardhat
            forge clean && forge install && forge build && forge test -vvvvv --gas-report

workflows:
  version: 2

  build-test:
    jobs:
      - npm_build-test-coverage
      - foundry_test:
          requires:
            - npm_build-test-coverage
