# Write a Github Actions workflow to build the Docker image
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Build the Docker image
          run: docker build -f Dockerfile -t aleph-vortex-app .